### ISSUE TITLE
BaseDotsIndicator.isNotEmpty KotlinNullPointerException

### ISSUE THREAD

**Issue by Yurdaaaaa** [tommybuonomo/dotsindicator#155]
```
Fatal Exception: kotlin.KotlinNullPointerException
       at com.tbuonomo.viewpagerdotsindicator.BaseDotsIndicator.isNotEmpty(BaseDotsIndicator.kt:301)
       at com.tbuonomo.viewpagerdotsindicator.BaseDotsIndicator$setViewPager$2.isNotEmpty(BaseDotsIndicator.kt:197)
       at com.tbuonomo.viewpagerdotsindicator.BaseDotsIndicator.refreshOnPageChangedListener(BaseDotsIndicator.kt:150)
       at com.tbuonomo.viewpagerdotsindicator.BaseDotsIndicator.access$refreshOnPageChangedListener(BaseDotsIndicator.kt:19)
       at com.tbuonomo.viewpagerdotsindicator.BaseDotsIndicator$refreshDots$1.run(BaseDotsIndicator.kt:145)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6977)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:910)
       
```
       
Anyway are u sure with your double bang operators? Its crashing your lib.

This was happening on version 4.1.2. Posting just in case u didnt fixed it.

**Comment by Yurdaaaaa** [comment]
@tommybuonomo hi, is this bug still relevant in newer versions?

**Comment by tommybuonomo** [comment]
Hello @Yurdaaaaa no this bug is not relevant anymore
