### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by shubhamrb** [tommybuonomo/dotsindicator#156]
Hi, i'm getting the classcastexception, can anyone help.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.frenzee.app, PID: 24493
    java.lang.ClassCastException: android.widget.RelativeLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
        at com.tbuonomo.viewpagerdotsindicator.DotsIndicator.addDot(DotsIndicator.kt:81)
        at com.tbuonomo.viewpagerdotsindicator.BaseDotsIndicator.addDots(BaseDotsIndicator.kt:139)
        at com.tbuonomo.viewpagerdotsindicator.BaseDotsIndicator.refreshDotsCount(BaseDotsIndicator.kt:117)
        at com.tbuonomo.viewpagerdotsindicator.BaseDotsIndicator.refreshDots$lambda-1(BaseDotsIndicator.kt:155)
        at com.tbuonomo.viewpagerdotsindicator.BaseDotsIndicator.$r8$lambda$IbXUyopBiP3Ry0kzvjhKkUywhU0(Unknown Source:0)
        at com.tbuonomo.viewpagerdotsindicator.BaseDotsIndicator$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by parthm1015** [comment]
got the same issue.

the problem here is in dot_layout file. in this layout , parent layout is relative layout but while casting in Dotsindicator file its trying to cast to Framelayout as mentioned in log above.
