### ISSUE TITLE
Layout render problem. I can't see layout preview.

### ISSUE THREAD

**Issue by BurakDizlek** [tommybuonomo/dotsindicator#42]
`java.lang.NoClassDefFoundError: android/support/animation/SpringAnimation
	at com.tbuonomo.viewpagerdotsindicator.WormDotsIndicator.setUpDotIndicator(WormDotsIndicator.java:133)
	at com.tbuonomo.viewpagerdotsindicator.WormDotsIndicator.refreshDots(WormDotsIndicator.java:105)
	at com.tbuonomo.viewpagerdotsindicator.WormDotsIndicator.onAttachedToWindow(WormDotsIndicator.java:100)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3397)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:335)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:391)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:195)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:540)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$5(RenderTask.java:666)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by Dhug95** [comment]
I have same problem. I can see everything on the phone but preview on Android Studio doesn't work.

**Comment by uniteddevil** [comment]
I have the exact same problem! 
`implementation 'com.tbuonomo.andrui:viewpagerdotsindicator:3.0.3'`

`<com.tbuonomo.viewpagerdotsindicator.SpringDotsIndicator
        android:id="@+id/dotsIndicator"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="140dp"
        app:dampingRatio="0.5"
        app:dotsColor="@color/colorWhite"
        app:dotsCornerRadius="4dp"
        app:dotsSize="8dp"
        app:dotsSpacing="3.5dp"
        app:dotsStrokeColor="@color/colorWhite"
        app:dotsStrokeWidth="1dp"
        app:dotsWidthFactor="2"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:progressMode="true"
        app:stiffness="300" />`

**Comment by tommybuonomo** [comment]
Fixed
